# Form implementation generated from reading ui file 'login_form.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LoginForm(object):
    def setupUi(self, LoginForm):
        LoginForm.setObjectName("LoginForm")
        LoginForm.resize(400, 300)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(LoginForm)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblUsername = QtWidgets.QLabel(parent=LoginForm)
        self.lblUsername.setObjectName("lblUsername")
        self.verticalLayout.addWidget(self.lblUsername)
        self.lnUsername = QtWidgets.QLineEdit(parent=LoginForm)
        self.lnUsername.setText("")
        self.lnUsername.setObjectName("lnUsername")
        self.verticalLayout.addWidget(self.lnUsername)
        self.lblUsername_2 = QtWidgets.QLabel(parent=LoginForm)
        self.lblUsername_2.setObjectName("lblUsername_2")
        self.verticalLayout.addWidget(self.lblUsername_2)
        self.lnPassword = QtWidgets.QLineEdit(parent=LoginForm)
        self.lnPassword.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhHiddenText|QtCore.Qt.InputMethodHint.ImhNoAutoUppercase|QtCore.Qt.InputMethodHint.ImhNoPredictiveText|QtCore.Qt.InputMethodHint.ImhSensitiveData)
        self.lnPassword.setText("")
        self.lnPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lnPassword.setObjectName("lnPassword")
        self.verticalLayout.addWidget(self.lnPassword)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btnLogin = QtWidgets.QPushButton(parent=LoginForm)
        self.btnLogin.setObjectName("btnLogin")
        self.horizontalLayout_3.addWidget(self.btnLogin)
        self.btnSignUp = QtWidgets.QPushButton(parent=LoginForm)
        self.btnSignUp.setObjectName("btnSignUp")
        self.horizontalLayout_3.addWidget(self.btnSignUp)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(LoginForm)
        QtCore.QMetaObject.connectSlotsByName(LoginForm)

    def retranslateUi(self, LoginForm):
        _translate = QtCore.QCoreApplication.translate
        LoginForm.setWindowTitle(_translate("LoginForm", "Form"))
        self.lblUsername.setText(_translate("LoginForm", "User name"))
        self.lblUsername_2.setText(_translate("LoginForm", "Password"))
        self.btnLogin.setText(_translate("LoginForm", "Login"))
        self.btnSignUp.setText(_translate("LoginForm", "Sign Up"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoginForm = QtWidgets.QWidget()
    ui = Ui_LoginForm()
    ui.setupUi(LoginForm)
    LoginForm.show()
    sys.exit(app.exec())
