# Form implementation generated from reading ui file 'login_failed_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_login_failed_dialog(object):
    def setupUi(self, login_failed_dialog):
        login_failed_dialog.setObjectName("login_failed_dialog")
        login_failed_dialog.resize(400, 300)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(login_failed_dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_login = QtWidgets.QLabel(parent=login_failed_dialog)
        self.lbl_login.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_login.setObjectName("lbl_login")
        self.verticalLayout.addWidget(self.lbl_login)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnRetry = QtWidgets.QPushButton(parent=login_failed_dialog)
        self.btnRetry.setObjectName("btnRetry")
        self.horizontalLayout.addWidget(self.btnRetry)
        self.btnCancel = QtWidgets.QPushButton(parent=login_failed_dialog)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout.addWidget(self.btnCancel)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(login_failed_dialog)
        QtCore.QMetaObject.connectSlotsByName(login_failed_dialog)

    def retranslateUi(self, login_failed_dialog):
        _translate = QtCore.QCoreApplication.translate
        login_failed_dialog.setWindowTitle(_translate("login_failed_dialog", "Dialog"))
        self.lbl_login.setText(_translate("login_failed_dialog", "Invalid login details"))
        self.btnRetry.setText(_translate("login_failed_dialog", "Try Again"))
        self.btnCancel.setText(_translate("login_failed_dialog", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    login_failed_dialog = QtWidgets.QDialog()
    ui = Ui_login_failed_dialog()
    ui.setupUi(login_failed_dialog)
    login_failed_dialog.show()
    sys.exit(app.exec())
