# Form implementation generated from reading ui file 'review_window.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_review_window(object):
    def setupUi(self, review_window):
        review_window.setObjectName("review_window")
        review_window.resize(768, 585)
        self.centralwidget = QtWidgets.QWidget(parent=review_window)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblSelect = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblSelect.setObjectName("lblSelect")
        self.verticalLayout.addWidget(self.lblSelect)
        self.cbMarketSelect = QtWidgets.QComboBox(parent=self.centralwidget)
        self.cbMarketSelect.setObjectName("cbMarketSelect")
        self.verticalLayout.addWidget(self.cbMarketSelect)
        self.lblScore = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblScore.setObjectName("lblScore")
        self.verticalLayout.addWidget(self.lblScore)
        self.cbScores = QtWidgets.QComboBox(parent=self.centralwidget)
        self.cbScores.setObjectName("cbScores")
        self.verticalLayout.addWidget(self.cbScores)
        self.lblText = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblText.setObjectName("lblText")
        self.verticalLayout.addWidget(self.lblText)
        self.tReviewBody = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.tReviewBody.setObjectName("tReviewBody")
        self.verticalLayout.addWidget(self.tReviewBody)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.btnReview = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnReview.setObjectName("btnReview")
        self.verticalLayout_9.addWidget(self.btnReview)
        self.horizontalLayout.addLayout(self.verticalLayout_9)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout.addLayout(self.horizontalLayout_6)
        review_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=review_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 768, 22))
        self.menubar.setObjectName("menubar")
        review_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=review_window)
        self.statusbar.setObjectName("statusbar")
        review_window.setStatusBar(self.statusbar)

        self.retranslateUi(review_window)
        QtCore.QMetaObject.connectSlotsByName(review_window)

    def retranslateUi(self, review_window):
        _translate = QtCore.QCoreApplication.translate
        review_window.setWindowTitle(_translate("review_window", "MainWindow"))
        self.lblSelect.setText(_translate("review_window", "Select a market to review"))
        self.lblScore.setText(_translate("review_window", "Assign a score"))
        self.lblText.setText(_translate("review_window", "Share your experience here (optional)"))
        self.btnReview.setText(_translate("review_window", "Submit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    review_window = QtWidgets.QMainWindow()
    ui = Ui_review_window()
    ui.setupUi(review_window)
    review_window.show()
    sys.exit(app.exec())
