# Form implementation generated from reading ui file 'review_pages.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_market_pages_window2(object):
    def setupUi(self, market_pages_window2):
        market_pages_window2.setObjectName("market_pages_window2")
        market_pages_window2.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=market_pages_window2)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tMPages = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.tMPages.setReadOnly(True)
        self.tMPages.setObjectName("tMPages")
        self.horizontalLayout.addWidget(self.tMPages)
        self.lblDReviews = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblDReviews.setObjectName("lblDReviews")
        self.horizontalLayout.addWidget(self.lblDReviews)
        self.cmDReviews = QtWidgets.QComboBox(parent=self.centralwidget)
        self.cmDReviews.setObjectName("cmDReviews")
        self.horizontalLayout.addWidget(self.cmDReviews)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        market_pages_window2.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=market_pages_window2)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        market_pages_window2.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=market_pages_window2)
        self.statusbar.setObjectName("statusbar")
        market_pages_window2.setStatusBar(self.statusbar)

        self.retranslateUi(market_pages_window2)
        QtCore.QMetaObject.connectSlotsByName(market_pages_window2)

    def retranslateUi(self, market_pages_window2):
        _translate = QtCore.QCoreApplication.translate
        market_pages_window2.setWindowTitle(_translate("market_pages_window2", "MainWindow"))
        self.lblDReviews.setText(_translate("market_pages_window2", "Select a user"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    market_pages_window2 = QtWidgets.QMainWindow()
    ui = Ui_market_pages_window2()
    ui.setupUi(market_pages_window2)
    market_pages_window2.show()
    sys.exit(app.exec())
