# Form implementation generated from reading ui file 'search_window.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SearchWindow(object):
    def setupUi(self, SearchWindow):
        SearchWindow.setObjectName("SearchWindow")
        SearchWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=SearchWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblCity = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblCity.setObjectName("lblCity")
        self.verticalLayout.addWidget(self.lblCity)
        self.lnCity = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lnCity.setObjectName("lnCity")
        self.verticalLayout.addWidget(self.lnCity)
        self.lblState = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblState.setObjectName("lblState")
        self.verticalLayout.addWidget(self.lblState)
        self.lnState = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lnState.setObjectName("lnState")
        self.verticalLayout.addWidget(self.lnState)
        self.lblZip = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblZip.setObjectName("lblZip")
        self.verticalLayout.addWidget(self.lblZip)
        self.lnZip = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lnZip.setObjectName("lnZip")
        self.verticalLayout.addWidget(self.lnZip)
        self.cbxCoords = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.cbxCoords.setObjectName("cbxCoords")
        self.verticalLayout.addWidget(self.cbxCoords)
        self.cbxMyCoords = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.cbxMyCoords.setObjectName("cbxMyCoords")
        self.verticalLayout.addWidget(self.cbxMyCoords)
        self.lblLimit = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblLimit.setObjectName("lblLimit")
        self.verticalLayout.addWidget(self.lblLimit)
        self.lnCoords = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lnCoords.setObjectName("lnCoords")
        self.verticalLayout.addWidget(self.lnCoords)
        self.lblResult = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblResult.setObjectName("lblResult")
        self.verticalLayout.addWidget(self.lblResult)
        self.lSearch = QtWidgets.QListWidget(parent=self.centralwidget)
        self.lSearch.setObjectName("lSearch")
        self.verticalLayout.addWidget(self.lSearch)
        self.btnSearch = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnSearch.setObjectName("btnSearch")
        self.verticalLayout.addWidget(self.btnSearch)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblLimit_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblLimit_2.setObjectName("lblLimit_2")
        self.horizontalLayout.addWidget(self.lblLimit_2)
        self.sbLimit = QtWidgets.QSpinBox(parent=self.centralwidget)
        self.sbLimit.setMaximum(9999)
        self.sbLimit.setObjectName("sbLimit")
        self.horizontalLayout.addWidget(self.sbLimit)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        SearchWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=SearchWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        SearchWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=SearchWindow)
        self.statusbar.setObjectName("statusbar")
        SearchWindow.setStatusBar(self.statusbar)

        self.retranslateUi(SearchWindow)
        QtCore.QMetaObject.connectSlotsByName(SearchWindow)

    def retranslateUi(self, SearchWindow):
        _translate = QtCore.QCoreApplication.translate
        SearchWindow.setWindowTitle(_translate("SearchWindow", "MainWindow"))
        self.lblCity.setText(_translate("SearchWindow", "Search by city"))
        self.lblState.setText(_translate("SearchWindow", "Search by state"))
        self.lblZip.setText(_translate("SearchWindow", "Search by zip"))
        self.cbxCoords.setText(_translate("SearchWindow", "Find closest"))
        self.cbxMyCoords.setText(_translate("SearchWindow", "Set my location coordinates"))
        self.lblLimit.setText(_translate("SearchWindow", "Type in the coodinates youd would like to perform search from"))
        self.lblResult.setText(_translate("SearchWindow", "Double-click the listed items for a more detailed view"))
        self.btnSearch.setText(_translate("SearchWindow", "Search"))
        self.lblLimit_2.setText(_translate("SearchWindow", "Search range"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SearchWindow = QtWidgets.QMainWindow()
    ui = Ui_SearchWindow()
    ui.setupUi(SearchWindow)
    SearchWindow.show()
    sys.exit(app.exec())
