# Form implementation generated from reading ui file 'widget_pop_up.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_widget_pop_up(object):
    def setupUi(self, widget_pop_up):
        widget_pop_up.setObjectName("widget_pop_up")
        widget_pop_up.resize(301, 234)
        self.horizontalLayout = QtWidgets.QHBoxLayout(widget_pop_up)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tPop = QtWidgets.QTextEdit(parent=widget_pop_up)
        self.tPop.setObjectName("tPop")
        self.verticalLayout_3.addWidget(self.tPop)
        self.btnPop = QtWidgets.QPushButton(parent=widget_pop_up)
        self.btnPop.setObjectName("btnPop")
        self.verticalLayout_3.addWidget(self.btnPop)
        self.horizontalLayout.addLayout(self.verticalLayout_3)

        self.retranslateUi(widget_pop_up)
        QtCore.QMetaObject.connectSlotsByName(widget_pop_up)

    def retranslateUi(self, widget_pop_up):
        _translate = QtCore.QCoreApplication.translate
        widget_pop_up.setWindowTitle(_translate("widget_pop_up", "Form"))
        self.btnPop.setText(_translate("widget_pop_up", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    widget_pop_up = QtWidgets.QWidget()
    ui = Ui_widget_pop_up()
    ui.setupUi(widget_pop_up)
    widget_pop_up.show()
    sys.exit(app.exec())
